~/ t.calcspeed
~/ puts speed in ul1 & color code in ul2
~/ DML 2/11/91
 1
 y
 ul1
 length*60/timau
  
 all
 4
 1
 y
 ul2
 0
  
 all
 4
 1
 y
 ul2
 1
  
 ul1=1,10
  
 4
 1
 y
 ul2
 2
  
 ul1=10.000001,20
  
 4
 1
 y
 ul2
 3
  
 ul1=20.000001,30
  
 4
 1
 y
 ul2
 4
  
 ul1=30.000001,40
  
 4
 1
 y
 ul2
 5
  
 ul1=40.000001,50
  
 4
 1
 y
 ul2
 6
  
 ul1=50.000001,99
  
 4
 6
 9
