 ~/ t.copyspd
 ~/ macro to copy capacity from another scenario to current scenario
 ~/ usage: emme2 clear 241 batch -m "t.copyspd $scencap"
 ~/ DML 5.14.92
 2            /copy attribute from another scenario
 %1%          /copy attribute from scenario %1%
 ul1          /attribute: speed stored in ul1
 ul1          /attribute of current scenario to save result
 all          /link types
 q
